# Generated by Django 6.1.1 on 2026-09-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_remove_disease_symptoms_remove_disease_treatment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='care',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='family',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='plant',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='origin',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
