# Generated by Django 6.1.1 on 2026-09-04 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_plant_care_plant_description_plant_family_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.AddField(
            model_name='plant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
