# Generated by Django 6.1.1 on 2026-09-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_delete_disease_plant_created_at_plant_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
